version: "3"
services:
  react-app:
    image: react-app-production:${ENV}
    restart: unless-stopped
    ports: 
      - "80:80"
      - "443:443"
    volumes:
      - caddy-data:/data
      - caddy-config:/config
    networks: 
      - subs
  api-server:
    image: api-server
    restart: unless-stopped
    env_file: ./backend/config/${ENV}.env
    ports: 
      - "5000:5000"
    networks:
      - subs
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: subs
    volumes:
      - ./server/pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - subs
  server:
    build: ./server 
    depends_on:
      - db
    links:
      - db
    env_file:
      - ./server/.env
    expose:
      - "4000"
    ports:
      - "4000:4000"
    networks:
      - subs
networks:
  subs:
    driver: bridge
volumes:
  mongo-data:
    driver: local
  caddy-data:
    driver: local
  caddy-config:
    driver: local