build-dev:
	docker build -t api-server -f Dockerfile.dev .

build-local: 
	docker build -t api-server -f Dockerfile.production .

build-production: 
	docker build -t api-server -f Dockerfile.production .